# PlayerVaults by https://github.com/drtshock/PlayerVaults/graphs/contributors
# Spigot page: https://www.spigotmc.org/resources/playervaultsx.51204/
# Made with love :3

# Debug mode
# This will print lots of spammy stuff to console.
# Should probably only enabled this if you're working with drtshock to fix something.
debug: false

# Lang files can be found in plugins/PlayerVaults/lang/
# Set the below value to be one of the files in there without .yml
# Currently can use: english, bulgarian, dutch, turkish
language: english

# Signs
# Do you want to enable signs?
# You can checkout the project page for info on what this is if you don't know.
# This can save some performance on servers with 250+ players if disabled.
signs-enabled: false

# Settings here are for economy integration. playervaults.free bypasses it.
economy:
  enabled: false
  
# Cost to create a vault. You can give players playervaults.free to bypass this.
  cost-to-create: 100
  cost-to-open: 10
  refund-on-delete: 50

# Blocked Items
# Here you can block items in vaults.
# You can give player's playervaults.bypassblockeditems permission to bypass this list.
# Ops also have an automatic bypass.
# Use material names. This does not work with ids.

# Should we even use this? If left to false, the list won't do anything.
blockitems: true

# Only effective if the above option is true.
blocked-items:
  - PUMPKIN
  - DIAMOND_BLOCK


# Cleanup
# Should we cleanup vaults that haven't been used in awhile?
# Only checks on restarts. Runs on another thread so it won't
#      lag the server.
#
# This will not touch the backups folder. You will have to delete those yourself.
cleanup:
  enable: false

  # If a file hasn't been edited for this long, we'll clean it up.
  # Time is in days.
  lastEdit: 30

backups:
  # If you don't want any backups created change this to false.
  enabled: true
