# PlayerVaults by drsthock and gomeow!
# http://dev.bukkit.org/server-mods/playervaults
# Made with love :3

# Whether or not you want to check for updates. 
# Will not download an update by default, that is your job :)
# We do not break between minecraft versions so auto updating should not be an issue.
# But it's always a smart idea to read changelogs and such first :)
check-update: true
download-update: false

# Settings here are for economy integration. playervaults.free bypasses it.
economy:
  enabled: false
  
# Cost to create a vault. You can give players playervaults.free to bypass this.
  cost-to-create: 100
  cost-to-open: 10
  refund-on-delete: 50

# Cleanup
# Should we cleanup vaults that haven't been used in awhile?
# Only checks on restarts. Runs on another thread so it won't
#      lag the server.
cleanup:
  enable: false

  # If a file hasn't been edited for this long, we'll clean it up.
  # Time is in days.
  lastEdit: 30